version: '3.8'

services:
  blog:
    image: ghost:5-alpine
    container_name: personal_blog
    restart: unless-stopped
    ports:
      - "2368:2368"
    environment:
      url: http://localhost:2368
    volumes:
      - ./blog_data:/var/lib/ghost/content

  db:
    image: mysql:8.0
    container_name: blog_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: example_password
    volumes:
      - ./mysql_data:/var/lib/mysql